import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays } from "lucide-react";

import BlogAdminLink from "@/components/blog/blog-admin-link";
import { blogArticles } from "@/lib/content/blog";
import { loadPublishedBlogArticles } from "@/lib/content/blog-data";

export const metadata = { title: "Construction Cost & Building Guides", description: "Plain-language Nigerian construction cost, BOQ, materials and procurement guides for homeowners and professionals." };
export const dynamic = "force-dynamic";

export default async function BlogPage() {
  const databaseArticles = await loadPublishedBlogArticles();
  const articles = databaseArticles ?? blogArticles;
  return <main className="min-h-screen bg-[#F5F7FA] pt-20"><section className="bg-[#081B36] text-white"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#E7B34B]">Charismak construction news &amp; guides</p><h1 className="mt-3 max-w-4xl text-4xl font-black md:text-6xl">Understand the cost before the work begins.</h1><p className="mt-5 max-w-3xl text-base leading-8 text-white/70">Construction news and practical explanations for homeowners, builders, artisans, suppliers and professionals—connected to the estimator and price tools.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/estimator" className="rounded-xl bg-[#C8320A] px-5 py-3 text-sm font-bold text-white">Estimate a project</Link><Link href="/prices" className="rounded-xl border border-white/25 px-5 py-3 text-sm font-bold text-white">Check price references</Link><BlogAdminLink /></div></div></section>{articles.length ? <section className="mx-auto grid max-w-7xl gap-5 px-5 py-12 md:grid-cols-2 md:px-8 xl:grid-cols-3">{articles.map((article) => <article key={article.slug} className="flex flex-col rounded-2xl border border-[#DCE4EC] bg-white p-6 shadow-[0_8px_26px_rgba(7,30,51,0.04)]"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#EAF2FF] text-[#175FC4]"><BookOpen className="h-5 w-5" /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.15em] text-[#C8320A]">{article.category}</p><h2 className="mt-2 text-xl font-bold leading-7 text-[#081B36]">{article.title}</h2><p className="mt-3 text-sm leading-6 text-[#617286]">{article.excerpt}</p><div className="mt-auto pt-6"><p className="flex items-center gap-2 text-[10px] text-[#7A8B9E]"><CalendarDays className="h-3.5 w-3.5" />{new Date(article.publishedAt).toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })} · {article.readTime}</p><Link href={`/blog/${article.slug}`} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#175FC4]">Read article <ArrowRight className="h-4 w-4" /></Link></div></article>)}</section> : <section className="mx-auto max-w-3xl px-5 py-20 text-center"><BookOpen className="mx-auto h-10 w-10 text-[#617286]" /><h2 className="mt-4 text-2xl font-black text-[#081B36]">Construction articles are being prepared</h2><p className="mt-3 text-sm leading-6 text-[#617286]">Please check back for the latest Charismak construction news and practical guides.</p></section>}</main>;
}
