import type { PriceCategory, PriceItem, RateTemplate } from "./models";

const updatedAt = "2026-08-09T00:00:00.000Z";

type CatalogRow = [
  id: string,
  code: string,
  description: string,
  category: PriceCategory,
  unit: string,
  starterRate: number,
];

// Broad Nigeria-first starter catalog. Rates are references for testing the
// workflow and are never presented as verified live quotations.
const rows: CatalogRow[] = [
  ["cement-42-5", "MAT-101", "Cement, 42.5 grade, 50 kg bag", "material", "bag", 12500],
  ["white-cement", "MAT-102", "White cement", "material", "bag", 28000],
  ["hydrated-lime", "MAT-103", "Hydrated lime", "material", "bag", 15000],
  ["concrete-admixture", "MAT-104", "Concrete plasticising admixture", "material", "litre", 4500],
  ["plaster-sand", "MAT-105", "Plastering sand", "material", "m³", 35000],
  ["quarry-dust", "MAT-106", "Quarry dust", "material", "m³", 40000],
  ["laterite", "MAT-107", "Selected lateritic filling", "material", "m³", 18000],
  ["hardcore", "MAT-108", "Hardcore filling", "material", "m³", 35000],
  ["stone-base", "MAT-109", "Crushed stone base course", "material", "m³", 52000],
  ["block-150", "MAT-110", "150 mm sandcrete block", "material", "nr", 750],
  ["block-100", "MAT-111", "100 mm sandcrete block", "material", "nr", 650],
  ["clay-brick", "MAT-112", "Burnt clay facing brick", "material", "nr", 650],
  ["interlocking-paver", "MAT-113", "60 mm concrete interlocking paving block", "material", "m²", 14500],
  ["concrete-kerb", "MAT-114", "Precast concrete road kerb", "material", "m", 6500],
  ["ready-mix-25", "MAT-115", "Ready-mixed concrete, grade 25", "material", "m³", 145000],
  ["ready-mix-30", "MAT-116", "Ready-mixed concrete, grade 30", "material", "m³", 158000],
  ["bamboo", "MAT-117", "Construction bamboo support", "material", "nr", 2500],
  ["mesh-a142", "MAT-118", "A142 welded reinforcement mesh", "material", "sheet", 68000],
  ["mesh-a193", "MAT-119", "A193 welded reinforcement mesh", "material", "sheet", 92000],
  ["mild-steel", "MAT-120", "Mild steel plate and sections", "material", "kg", 1700],
  ["structural-steel", "MAT-121", "Structural steel sections", "material", "kg", 1900],
  ["steel-pipe-50", "MAT-122", "50 mm mild-steel hollow section", "material", "m", 7500],
  ["aluminium-section", "MAT-123", "Powder-coated aluminium framing section", "material", "kg", 7500],
  ["marine-plywood", "MAT-124", "18 mm marine plywood sheet", "material", "sheet", 52000],
  ["timber-50x100", "MAT-125", "50 × 100 mm treated timber", "material", "m", 2200],
  ["timber-50x150", "MAT-126", "50 × 150 mm treated timber", "material", "m", 3200],
  ["form-release-oil", "MAT-127", "Formwork release oil", "material", "litre", 3000],
  ["stone-coated-roof", "MAT-128", "Stone-coated steel roofing tile", "material", "m²", 19000],
  ["roof-ridge", "MAT-129", "Roof ridge and flashing accessory", "material", "m", 8500],
  ["roofing-felt", "MAT-130", "Roofing underlay/felt", "material", "m²", 2500],
  ["bitumen-membrane", "MAT-131", "Torch-on bituminous waterproofing membrane", "material", "m²", 8500],
  ["dpm-1000", "MAT-132", "1000 gauge polythene damp-proof membrane", "material", "m²", 1200],
  ["dpc-roll", "MAT-133", "Bituminous damp-proof course", "material", "m", 1800],
  ["waterstop", "MAT-134", "PVC waterstop", "material", "m", 8500],
  ["silicone-sealant", "MAT-135", "General-purpose silicone sealant", "material", "tube", 5500],
  ["flush-door", "MAT-136", "Selected internal flush door leaf", "material", "nr", 85000],
  ["security-door", "MAT-137", "Steel security entrance door set", "material", "nr", 450000],
  ["aluminium-window", "MAT-138", "Powder-coated aluminium glazed window", "material", "m²", 125000],
  ["glass-6mm", "MAT-139", "6 mm clear float glass", "material", "m²", 38000],
  ["porcelain-tile", "MAT-140", "Selected porcelain floor tile", "material", "m²", 18000],
  ["wall-tile", "MAT-141", "Selected ceramic wall tile", "material", "m²", 14000],
  ["tile-grout", "MAT-142", "Tile grout", "material", "kg", 1800],
  ["gypsum-board", "MAT-143", "12.5 mm gypsum plasterboard", "material", "sheet", 18000],
  ["cement-board", "MAT-144", "Fibre-cement board", "material", "sheet", 32000],
  ["pop-cement", "MAT-145", "Plaster of Paris", "material", "bag", 15000],
  ["ceiling-grid", "MAT-146", "Suspended ceiling grid system", "material", "m²", 8000],
  ["paint-primer", "MAT-147", "Wall primer/sealer", "material", "litre", 4200],
  ["satin-paint", "MAT-148", "Satin/emulsion finish paint", "material", "litre", 6500],
  ["gloss-paint", "MAT-149", "Gloss paint for timber/metal", "material", "litre", 7500],
  ["pvc-pipe-25", "PLU-101", "25 mm uPVC pressure pipe", "material", "m", 1800],
  ["pvc-pipe-50", "PLU-102", "50 mm uPVC waste pipe", "material", "m", 3200],
  ["pvc-pipe-75", "PLU-103", "75 mm uPVC waste pipe", "material", "m", 4500],
  ["pvc-pipe-110", "PLU-104", "110 mm uPVC soil pipe", "material", "m", 7000],
  ["floor-drain", "PLU-105", "Stainless-steel floor drain", "material", "nr", 18000],
  ["wc-set", "PLU-106", "Complete WC suite", "material", "nr", 180000],
  ["wash-hand-basin", "PLU-107", "Wash-hand basin with fittings", "material", "nr", 120000],
  ["shower-mixer", "PLU-108", "Shower mixer set", "material", "nr", 95000],
  ["water-tank-2000", "PLU-109", "2,000 litre polyethylene water tank", "material", "nr", 320000],
  ["water-pump", "PLU-110", "Domestic water booster pump", "material", "nr", 280000],
  ["cable-1-5", "ELE-101", "1.5 mm² copper cable", "material", "m", 650],
  ["cable-4", "ELE-102", "4 mm² copper cable", "material", "m", 1450],
  ["cable-6", "ELE-103", "6 mm² copper cable", "material", "m", 2200],
  ["cable-10", "ELE-104", "10 mm² copper cable", "material", "m", 3900],
  ["cable-16", "ELE-105", "16 mm² copper cable", "material", "m", 6200],
  ["lighting-switch", "ELE-106", "Lighting switch", "material", "nr", 4500],
  ["led-light", "ELE-107", "LED light fitting", "material", "nr", 12000],
  ["distribution-board", "ELE-108", "Electrical distribution board", "material", "nr", 95000],
  ["mcb", "ELE-109", "Miniature circuit breaker", "material", "nr", 8500],
  ["earthing-set", "ELE-110", "Complete earth electrode set", "material", "set", 85000],
  ["solar-panel", "ELE-111", "Solar PV panel", "material", "nr", 165000],
  ["inverter-5kva", "ELE-112", "5 kVA hybrid inverter", "material", "nr", 850000],
  ["battery-5kwh", "ELE-113", "5 kWh lithium battery", "material", "nr", 1500000],
  ["split-ac-1-5hp", "MEC-101", "1.5 HP split air-conditioning unit", "material", "nr", 650000],
  ["refrigerant-pipe", "MEC-102", "Insulated refrigerant copper pipe pair", "material", "m", 18000],
  ["galvanized-duct", "MEC-103", "Galvanized sheet-metal ductwork", "material", "m²", 35000],
  ["split-ac-1hp", "MEC-104", "1.0 HP split air-conditioning unit", "material", "nr", 520000],
  ["split-ac-2hp", "MEC-105", "2.0 HP split air-conditioning unit", "material", "nr", 780000],
  ["split-ac-2-5hp", "MEC-106", "2.5 HP split air-conditioning unit", "material", "nr", 980000],
  ["split-ac-3hp", "MEC-107", "3.0 HP split air-conditioning unit", "material", "nr", 1250000],
  ["split-ac-5hp", "MEC-108", "5.0 HP split air-conditioning unit", "material", "nr", 1850000],
  ["cassette-ac-2hp", "MEC-109", "2.0 HP ceiling-cassette air-conditioning unit", "material", "nr", 1250000],
  ["cassette-ac-3hp", "MEC-110", "3.0 HP ceiling-cassette air-conditioning unit", "material", "nr", 1650000],
  ["cassette-ac-5hp", "MEC-111", "5.0 HP ceiling-cassette air-conditioning unit", "material", "nr", 2450000],
  ["floor-ac-3hp", "MEC-112", "3.0 HP floor-standing air-conditioning unit", "material", "nr", 1500000],
  ["floor-ac-5hp", "MEC-113", "5.0 HP floor-standing air-conditioning unit", "material", "nr", 2200000],
  ["vrf-indoor-unit", "MEC-114", "VRF indoor air-conditioning unit allowance", "material", "nr", 1350000],
  ["fire-extinguisher", "FIR-101", "6 kg dry-powder fire extinguisher", "material", "nr", 55000],
  ["sprinkler-head", "FIR-102", "Automatic fire sprinkler head", "material", "nr", 18000],
  ["geotextile", "CIV-101", "Non-woven geotextile membrane", "material", "m²", 4500],
  ["concrete-pipe-600", "CIV-102", "600 mm precast concrete drainage pipe", "material", "m", 85000],
  ["gabion-basket", "CIV-103", "Gabion basket including tying wire", "material", "m³", 65000],
  ["bitumen", "CIV-104", "Bitumen binder", "material", "litre", 1800],
  ["chainlink", "FEN-101", "Chain-link fencing mesh", "material", "m²", 8500],
  ["razor-wire", "FEN-102", "Razor/barbed security wire", "material", "m", 5500],
  ["electric-fence-kit", "FEN-103", "Electric-fence energizer and accessories", "material", "set", 650000],
  ["mason-day", "LAB-101", "Mason/bricklayer", "labour", "day", 18000],
  ["carpenter-day", "LAB-102", "Carpenter/joiner", "labour", "day", 20000],
  ["iron-bender-day", "LAB-103", "Steel fixer/iron bender", "labour", "day", 20000],
  ["electrician-day", "LAB-104", "Electrician", "labour", "day", 22000],
  ["plumber-day", "LAB-105", "Plumber/pipe fitter", "labour", "day", 22000],
  ["painter-day", "LAB-106", "Painter/decorator", "labour", "day", 18000],
  ["tiler-day", "LAB-107", "Tiler", "labour", "day", 22000],
  ["welder-day", "LAB-108", "Welder/fabricator", "labour", "day", 25000],
  ["roofer-day", "LAB-109", "Roofer", "labour", "day", 22000],
  ["general-labour-day", "LAB-110", "General construction labourer", "labour", "day", 10000],
  ["site-supervisor-day", "LAB-111", "Site supervisor", "labour", "day", 35000],
  ["excavator-hour", "PLT-101", "Hydraulic excavator with operator", "plant", "hour", 65000],
  ["backhoe-hour", "PLT-102", "Backhoe loader with operator", "plant", "hour", 50000],
  ["bulldozer-hour", "PLT-103", "Bulldozer with operator", "plant", "hour", 85000],
  ["grader-hour", "PLT-104", "Motor grader with operator", "plant", "hour", 85000],
  ["roller-hour", "PLT-105", "Vibratory roller with operator", "plant", "hour", 55000],
  ["tipper-trip", "PLT-106", "10-15 tonne tipper haulage", "plant", "trip", 85000],
  ["mobile-crane-hour", "PLT-107", "Mobile crane with operator", "plant", "hour", 180000],
  ["generator-day", "PLT-108", "Site generator hire", "plant", "day", 45000],
  ["concrete-vibrator-day", "PLT-109", "Concrete vibrator hire", "plant", "day", 20000],
  ["scaffold-m2", "PLT-110", "Tubular scaffolding hire", "plant", "m²/week", 2500],
  ["borehole-subcontract", "SUB-101", "Complete borehole drilling and development", "subcontract", "item", 3500000],
  ["aluminium-subcontract", "SUB-102", "Aluminium glazing supply and installation", "subcontract", "m²", 145000],
  ["ac-install-subcontract", "SUB-103", "Split AC installation and commissioning", "subcontract", "nr", 120000],
];

export const AFRICA_PRICE_ITEMS: PriceItem[] = rows.map(
  ([id, code, description, category, unit, starterRate]) => ({
    id,
    code,
    description,
    category,
    unit,
    rate: starterRate,
    defaultRate: starterRate,
    currency: "NGN",
    countryCode: "NG",
    region: "FCT",
    location: "Abuja",
    source: "Charismak Nigeria starter reference - verify before commercial use",
    sourceUrl: null,
    confidence: "starter",
    updatedAt,
    active: true,
  }),
);

const component = (
  id: string,
  priceItemId: string,
  description: string,
  category: PriceCategory,
  quantityPerUnit: number,
) => ({ id, priceItemId, description, category, quantityPerUnit });

const concreteRateTemplate = (
  id: string,
  code: string,
  name: string,
  description: string,
  ratios: [number, number, number],
  waterLitresPerM3: number,
  defaultUnitRate: number,
): RateTemplate => {
  const prefix = id.replace(/[^a-z0-9]+/gi, "-");
  const ids = {
    cement: `${prefix}-cement`,
    sand: `${prefix}-sand`,
    aggregate: `${prefix}-aggregate`,
    water: `${prefix}-water`,
  };
  return {
    id,
    code,
    name,
    description,
    unit: "m³",
    module: "concrete",
    category: "substructure",
    defaultUnitRate,
    diagramType: "concrete",
    assumptions: [
      { id: "cementRatio", label: "Cement ratio", defaultValue: ratios[0], min: 0, step: 0.1 },
      { id: "sandRatio", label: "Sand ratio", defaultValue: ratios[1], min: 0, step: 0.1 },
      { id: "aggregateRatio", label: "Aggregate ratio", defaultValue: ratios[2], min: 0, step: 0.1 },
      { id: "dryVolumeFactor", label: "Dry-volume factor", defaultValue: 1.54, min: 1, step: 0.01 },
      { id: "cementBagVolumeM3", label: "Cement bag volume", unit: "m³/bag", defaultValue: 0.0347, min: 0.001, step: 0.0001 },
      { id: "materialWastagePercent", label: "Material wastage", unit: "%", defaultValue: 5, min: 0, step: 0.5 },
      { id: "waterLitresPerM3", label: "Water allowance", unit: "L/m³", defaultValue: waterLitresPerM3, min: 0, step: 1 },
    ],
    formula: {
      type: "concrete-ratio",
      componentIds: ids,
    },
    components: [
      component(ids.cement, "cement-50kg", "Cement", "material", 0),
      component(ids.sand, "sharp-sand", "Sharp sand", "material", 0),
      component(ids.aggregate, "granite-aggregate", "Coarse aggregate", "material", 0),
      component(ids.water, "water", "Water", "material", waterLitresPerM3),
      component(`${prefix}-labour`, "concrete-labour", "Mixing and placing labour", "labour", 1),
      component(`${prefix}-plant`, "concrete-mixer", "Mixer and small plant", "plant", 1),
    ],
  };
};

const acRateTemplate = (
  id: string,
  code: string,
  name: string,
  equipmentPriceItemId: string,
  defaultUnitRate: number,
  pipeLengthM = 5,
): RateTemplate => ({
  id,
  code,
  name,
  description: `Supply, install, connect, test and commission ${name.toLowerCase()}.`,
  unit: "nr",
  module: "mechanical",
  category: "mechanical",
  defaultUnitRate,
  diagramType: "mechanical",
  assumptions: [
    { id: "refrigerantPipeLengthM", label: "Refrigerant pipe run", unit: "m", defaultValue: pipeLengthM, min: 0, step: 0.5 },
    { id: "installationUnits", label: "Installation subcontract allowance", unit: "unit", defaultValue: 1, min: 0, step: 0.1 },
  ],
  formula: {
    type: "component-assumptions",
    componentMappings: {
      refrigerantPipeLengthM: `${id}-pipe`,
      installationUnits: `${id}-install`,
    },
  },
  components: [
    component(`${id}-unit`, equipmentPriceItemId, "Air-conditioning equipment", "material", 1),
    component(`${id}-pipe`, "refrigerant-pipe", "Insulated refrigerant pipe pair", "material", pipeLengthM),
    component(`${id}-install`, "ac-install-subcontract", "Installation and commissioning", "subcontract", 1),
  ],
});

export const AFRICA_RATE_TEMPLATES: RateTemplate[] = [
  concreteRateTemplate("concrete-1-3-6-blinding", "RATE-CON-003", "1:3:6 Concrete Blinding", "Mix, place and compact nominal 1:3:6 lean concrete blinding.", [1, 3, 6], 180, 115000),
  concreteRateTemplate("concrete-1-4-8-blinding", "RATE-CON-004", "1:4:8 Lean Concrete Blinding", "Mix, place and compact nominal 1:4:8 lean concrete blinding.", [1, 4, 8], 190, 102000),
  concreteRateTemplate("cement-sand-1-10-blinding", "RATE-CON-005", "1:10 Cement-Sand Blinding", "Place cement-sand blinding or stabilised layer using an editable 1:10 starting ratio.", [1, 10, 0], 190, 85000),
  concreteRateTemplate("concrete-1-1-5-3", "RATE-CON-006", "1:1.5:3 Structural Concrete", "Mix, place and compact nominal 1:1.5:3 structural concrete.", [1, 1.5, 3], 160, 155000),
  concreteRateTemplate("concrete-custom-mix", "RATE-CON-007", "Custom Concrete Mix", "Configure cement, sand, aggregate, dry-volume, wastage and water assumptions for the specific element.", [1, 2, 4], 166.43, 135000),
  { id: "blockwork-150", code: "RATE-BLK-002", name: "150 mm Blockwork", description: "Provide and lay 150 mm sandcrete blockwork in cement-sand mortar.", unit: "m²", module: "blockwork", category: "walls", defaultUnitRate: 13500, diagramType: "blockwork", components: [component("b150-block", "block-150", "150 mm blocks", "material", 10.5), component("b150-cement", "cement-50kg", "Mortar cement", "material", 0.12), component("b150-sand", "sharp-sand", "Mortar sand", "material", 0.017), component("b150-lab", "blockwork-labour", "Block laying labour", "labour", 1)] },
  { id: "ready-mix-grade-25", code: "RATE-CON-002", name: "Grade 25 Ready-Mixed Concrete", description: "Supply, place, compact and cure grade 25 ready-mixed concrete.", unit: "m³", module: "concrete", category: "superstructure", defaultUnitRate: 175000, diagramType: "concrete", components: [component("rm25-concrete", "ready-mix-25", "Grade 25 ready mix", "material", 1.03), component("rm25-lab", "concrete-labour", "Placing labour", "labour", 1), component("rm25-vib", "concrete-vibrator-day", "Vibration allowance", "plant", 0.08)] },
  { id: "interlocking-paving", code: "RATE-EXT-001", name: "Interlocking Concrete Paving", description: "Prepare bedding and lay 60 mm interlocking concrete paving blocks.", unit: "m²", module: "external", category: "external", defaultUnitRate: 22500, diagramType: "finishes", components: [component("pav-block", "interlocking-paver", "Paving blocks", "material", 1.05), component("pav-sand", "sharp-sand", "Bedding sand", "material", 0.05), component("pav-lab", "mason-day", "Paving labour", "labour", 0.15)] },
  { id: "floor-screed", code: "RATE-FIN-004", name: "Cement-Sand Floor Screed", description: "Lay and finish cement-sand floor screed to prepared base.", unit: "m²", module: "finishes", category: "finishes", defaultUnitRate: 6500, diagramType: "finishes", components: [component("scr-cement", "cement-50kg", "Cement", "material", 0.1), component("scr-sand", "sharp-sand", "Sharp sand", "material", 0.022), component("scr-lab", "mason-day", "Screeding labour", "labour", 0.1)] },
  { id: "porcelain-floor-tiling", code: "RATE-FIN-005", name: "Porcelain Floor Tiling", description: "Lay selected porcelain tiles with adhesive and grout.", unit: "m²", module: "finishes", category: "finishes", defaultUnitRate: 32000, diagramType: "finishes", components: [component("por-tile", "porcelain-tile", "Porcelain tiles", "material", 1.05), component("por-adh", "tile-adhesive", "Tile adhesive", "material", 0.22), component("por-grout", "tile-grout", "Tile grout", "material", 0.3), component("por-lab", "tiling-labour", "Tiling labour", "labour", 1)] },
  { id: "gypsum-ceiling", code: "RATE-FIN-006", name: "Suspended Gypsum Ceiling", description: "Provide gypsum board suspended ceiling including framing and finishing.", unit: "m²", module: "finishes", category: "finishes", defaultUnitRate: 26000, diagramType: "finishes", components: [component("gyp-board", "gypsum-board", "Gypsum board allocation", "material", 0.38), component("gyp-grid", "ceiling-grid", "Framing system", "material", 1), component("gyp-lab", "carpenter-day", "Ceiling labour", "labour", 0.18)] },
  { id: "torch-waterproofing", code: "RATE-WPF-001", name: "Torch-On Waterproofing", description: "Prepare substrate and apply torch-on bituminous membrane.", unit: "m²", module: "waterproofing", category: "finishes", defaultUnitRate: 14500, diagramType: "finishes", components: [component("wpf-mem", "bitumen-membrane", "Membrane including laps", "material", 1.1), component("wpf-lab", "general-labour-day", "Application labour", "labour", 0.12)] },
  { id: "aluminium-window-installed", code: "RATE-WIN-001", name: "Aluminium Glazed Window", description: "Provide and install powder-coated aluminium glazed window complete.", unit: "m²", module: "windows", category: "doors-windows", defaultUnitRate: 145000, diagramType: "custom", components: [component("win-sub", "aluminium-subcontract", "Aluminium glazing subcontract", "subcontract", 1)] },
  { id: "flush-door-installed", code: "RATE-DOR-001", name: "Internal Flush Door Set", description: "Provide and hang selected internal flush door complete with frame and ironmongery allowance.", unit: "nr", module: "doors", category: "doors-windows", defaultUnitRate: 165000, diagramType: "custom", components: [component("door-leaf", "flush-door", "Flush door leaf", "material", 1), component("door-lab", "carpenter-day", "Installation labour", "labour", 1)] },
  { id: "security-door-installed", code: "RATE-DOR-002", name: "Steel Security Door Set", description: "Provide and install steel security entrance door set.", unit: "nr", module: "doors", category: "doors-windows", defaultUnitRate: 520000, diagramType: "custom", components: [component("sec-door", "security-door", "Security door set", "material", 1), component("sec-lab", "welder-day", "Installation labour", "labour", 1)] },
  { id: "stone-coated-roofing", code: "RATE-ROF-002", name: "Stone-Coated Roof Covering", description: "Supply and fix stone-coated steel roofing tiles with accessories.", unit: "m²", module: "roofing", category: "roof", defaultUnitRate: 30000, diagramType: "roofing", components: [component("scr-tile", "stone-coated-roof", "Roof tiles including waste", "material", 1.1), component("scr-ridge", "roof-ridge", "Ridges and flashings", "material", 0.12), component("scr-lab", "roofing-labour", "Roofing labour", "labour", 1)] },
  { id: "structural-steel-installed", code: "RATE-STE-001", name: "Fabricated Structural Steelwork", description: "Supply, fabricate, prime and erect structural steelwork.", unit: "kg", module: "steelwork", category: "frame", defaultUnitRate: 3200, diagramType: "reinforcement", components: [component("steel-mat", "structural-steel", "Structural steel", "material", 1.05), component("steel-lab", "welder-day", "Fabrication labour", "labour", 0.02), component("steel-plant", "mobile-crane-hour", "Erection plant allowance", "plant", 0.002)] },
  { id: "lighting-point", code: "RATE-ELE-002", name: "Lighting Point", description: "Wiring, conduit, switch, termination, testing and commissioning to one lighting point.", unit: "point", module: "electrical", category: "electrical", defaultUnitRate: 48000, diagramType: "electrical", components: [component("lgt-cable", "cable-1-5", "1.5 mm² cable", "material", 12), component("lgt-conduit", "conduit-20", "20 mm conduit", "material", 8), component("lgt-switch", "lighting-switch", "Switch", "material", 1), component("lgt-lab", "electrical-point-labour", "Installation labour", "labour", 1), component("lgt-test", "electrical-testing", "Testing", "labour", 1)] },
  { id: "distribution-board-installed", code: "RATE-ELE-003", name: "Distribution Board", description: "Provide, install, label, test and commission distribution board with starter breaker allowance.", unit: "nr", module: "electrical", category: "electrical", defaultUnitRate: 185000, diagramType: "electrical", components: [component("db-board", "distribution-board", "Distribution board", "material", 1), component("db-mcb", "mcb", "Circuit breakers", "material", 8), component("db-lab", "electrician-day", "Installation labour", "labour", 1)] },
  { id: "solar-5kva-system", code: "RATE-ELE-004", name: "5 kVA Solar/Inverter System", description: "Supply, install and commission starter 5 kVA hybrid power system.", unit: "set", module: "electrical", category: "electrical", defaultUnitRate: 4200000, diagramType: "electrical", components: [component("sol-inv", "inverter-5kva", "Hybrid inverter", "material", 1), component("sol-bat", "battery-5kwh", "Lithium batteries", "material", 2), component("sol-pan", "solar-panel", "Solar panels", "material", 8), component("sol-lab", "electrician-day", "Installation labour", "labour", 5)] },
  { id: "wc-suite-installed", code: "RATE-PLU-001", name: "WC Suite", description: "Provide and install complete WC suite including connection and testing.", unit: "nr", module: "plumbing", category: "mechanical", defaultUnitRate: 245000, diagramType: "mechanical", components: [component("wc-set", "wc-set", "WC suite", "material", 1), component("wc-lab", "plumber-day", "Installation labour", "labour", 1)] },
  { id: "wash-basin-installed", code: "RATE-PLU-002", name: "Wash-Hand Basin", description: "Provide and install wash-hand basin complete with tap, waste and connections.", unit: "nr", module: "plumbing", category: "mechanical", defaultUnitRate: 185000, diagramType: "mechanical", components: [component("whb-set", "wash-hand-basin", "Basin and fittings", "material", 1), component("whb-lab", "plumber-day", "Installation labour", "labour", 1)] },
  acRateTemplate("split-ac-installed", "RATE-MEC-003", "1.5 HP Split AC", "split-ac-1-5hp", 850000),
  acRateTemplate("split-ac-1hp-installed", "RATE-MEC-004", "1.0 HP Split AC", "split-ac-1hp", 720000),
  acRateTemplate("split-ac-2hp-installed", "RATE-MEC-005", "2.0 HP Split AC", "split-ac-2hp", 980000),
  acRateTemplate("split-ac-2-5hp-installed", "RATE-MEC-006", "2.5 HP Split AC", "split-ac-2-5hp", 1200000),
  acRateTemplate("split-ac-3hp-installed", "RATE-MEC-007", "3.0 HP Split AC", "split-ac-3hp", 1500000, 6),
  acRateTemplate("split-ac-5hp-installed", "RATE-MEC-008", "5.0 HP Split AC", "split-ac-5hp", 2200000, 7),
  acRateTemplate("cassette-ac-2hp-installed", "RATE-MEC-009", "2.0 HP Ceiling Cassette AC", "cassette-ac-2hp", 1520000, 6),
  acRateTemplate("cassette-ac-3hp-installed", "RATE-MEC-010", "3.0 HP Ceiling Cassette AC", "cassette-ac-3hp", 1950000, 7),
  acRateTemplate("cassette-ac-5hp-installed", "RATE-MEC-011", "5.0 HP Ceiling Cassette AC", "cassette-ac-5hp", 2850000, 8),
  acRateTemplate("floor-ac-3hp-installed", "RATE-MEC-012", "3.0 HP Floor-Standing AC", "floor-ac-3hp", 1800000, 6),
  acRateTemplate("floor-ac-5hp-installed", "RATE-MEC-013", "5.0 HP Floor-Standing AC", "floor-ac-5hp", 2600000, 8),
  acRateTemplate("vrf-indoor-installed", "RATE-MEC-014", "VRF Indoor Unit", "vrf-indoor-unit", 1680000, 10),
  { id: "fire-extinguisher-installed", code: "RATE-FIR-001", name: "Fire Extinguisher", description: "Provide, mount, label and commission dry-powder fire extinguisher.", unit: "nr", module: "fire", category: "mechanical", defaultUnitRate: 70000, diagramType: "mechanical", components: [component("fire-ext", "fire-extinguisher", "Fire extinguisher", "material", 1), component("fire-lab", "general-labour-day", "Mounting labour", "labour", 0.1)] },
  { id: "chainlink-fence", code: "RATE-FEN-001", name: "Chain-Link Fence", description: "Provide and install chain-link fencing mesh to prepared posts.", unit: "m²", module: "fence", category: "fence-security", defaultUnitRate: 14500, diagramType: "fence", components: [component("clf-mesh", "chainlink", "Chain-link mesh", "material", 1.05), component("clf-wire", "binding-wire", "Tying wire", "material", 0.05), component("clf-lab", "general-labour-day", "Installation labour", "labour", 0.12)] },
  { id: "razor-wire-installed", code: "RATE-FEN-002", name: "Razor-Wire Security Topping", description: "Provide and install razor-wire security topping complete with supports.", unit: "m", module: "fence", category: "fence-security", defaultUnitRate: 9500, diagramType: "fence", components: [component("raz-wire", "razor-wire", "Razor wire", "material", 1.05), component("raz-lab", "welder-day", "Installation labour", "labour", 0.04)] },
  { id: "stone-base-course", code: "RATE-CIV-001", name: "Crushed Stone Base Course", description: "Provide, spread, water and compact crushed stone base course.", unit: "m³", module: "civil", category: "external", defaultUnitRate: 75000, diagramType: "excavation", components: [component("base-mat", "stone-base", "Stone base", "material", 1.15), component("base-roller", "roller-hour", "Compaction plant", "plant", 0.15), component("base-lab", "general-labour-day", "Labour", "labour", 0.2)] },
  { id: "concrete-drainage-pipe", code: "RATE-CIV-002", name: "600 mm Concrete Drainage Pipe", description: "Excavate, bed, lay and joint 600 mm precast concrete drainage pipe.", unit: "m", module: "civil", category: "external", defaultUnitRate: 145000, diagramType: "mechanical", components: [component("drn-pipe", "concrete-pipe-600", "Concrete pipe", "material", 1), component("drn-sand", "sharp-sand", "Bedding sand", "material", 0.15), component("drn-plant", "excavator-hour", "Excavation plant", "plant", 0.12), component("drn-lab", "general-labour-day", "Laying labour", "labour", 0.25)] },
];
