import type {
  PriceItem,
  RateAssumptionDefinition,
  RateTemplate,
} from "./models";
import { AFRICA_PRICE_ITEMS, AFRICA_RATE_TEMPLATES } from "./africa-catalog";

const createdAt = "2026-08-09T00:00:00.000Z";

// Starter references make the workflow testable immediately. They are deliberately
// labelled as references, not verified live market quotations.
const starterRates: Record<string, number> = {
  "cement-50kg": 11500,
  "sharp-sand": 32000,
  "granite-aggregate": 65000,
  water: 15,
  "block-225": 900,
  "reinforcement-steel": 1550,
  "binding-wire": 2200,
  "formwork-sheet": 40000,
  "formwork-timber": 2200,
  nails: 2500,
  "concrete-labour": 25000,
  "blockwork-labour": 6000,
  "rebar-labour": 500,
  "formwork-labour": 6500,
  "excavation-labour": 6000,
  "concrete-mixer": 6000,
  "plaster-labour": 4000,
  "painting-labour": 1800,
  "tiling-labour": 5500,
  "emulsion-paint": 5000,
  "wall-filler": 1500,
  "floor-tile": 14000,
  "tile-adhesive": 12000,
  "cable-2-5": 900,
  "conduit-20": 800,
  "socket-13a": 8000,
  "back-box": 2000,
  "electrical-point-labour": 12000,
  "electrical-testing": 2000,
  "ppr-pipe-25": 3000,
  "ppr-fitting-allowance": 12000,
  "soil-pipe-110": 7000,
  "soil-fitting-allowance": 10000,
  "plumbing-point-labour": 15000,
  "pipework-labour": 2500,
  "longspan-roof-sheet": 17000,
  "roofing-accessories": 15000,
  "roofing-labour": 3500,
};

const CORE_PRICE_ITEMS: PriceItem[] = [
  ["cement-50kg", "MAT-001", "Cement, 50 kg bag", "material", "bag"],
  ["sharp-sand", "MAT-002", "Sharp sand", "material", "m³"],
  ["granite-aggregate", "MAT-003", "Granite coarse aggregate", "material", "m³"],
  ["water", "MAT-004", "Construction water", "material", "litre"],
  ["block-225", "MAT-005", "225 mm sandcrete block", "material", "nr"],
  ["reinforcement-steel", "MAT-006", "High-yield reinforcement steel", "material", "kg"],
  ["binding-wire", "MAT-007", "Binding wire", "material", "kg"],
  ["formwork-sheet", "MAT-008", "Formwork plywood sheet 1.22 × 2.44 m", "material", "sheet"],
  ["formwork-timber", "MAT-009", "Formwork support timber", "material", "m"],
  ["nails", "MAT-010", "Assorted nails", "material", "kg"],
  ["concrete-labour", "LAB-001", "Concrete mixing, placing and compaction labour", "labour", "m³"],
  ["blockwork-labour", "LAB-002", "225 mm block laying labour", "labour", "m²"],
  ["rebar-labour", "LAB-003", "Reinforcement cutting, bending and fixing labour", "labour", "kg"],
  ["formwork-labour", "LAB-004", "Formwork erection and striking labour", "labour", "m²"],
  ["excavation-labour", "LAB-005", "Manual excavation labour in normal ground", "labour", "m³"],
  ["concrete-mixer", "PLT-001", "Concrete mixer and small plant", "plant", "m³"],
  ["plaster-labour", "LAB-006", "Internal/external plastering labour", "labour", "m²"],
  ["painting-labour", "LAB-007", "Surface preparation and painting labour", "labour", "m²"],
  ["tiling-labour", "LAB-008", "Floor/wall tiling labour", "labour", "m²"],
  ["emulsion-paint", "MAT-011", "Emulsion paint", "material", "litre"],
  ["wall-filler", "MAT-012", "Wall filler/putty", "material", "kg"],
  ["floor-tile", "MAT-013", "Selected floor tile", "material", "m²"],
  ["tile-adhesive", "MAT-014", "Tile adhesive, 20 kg bag", "material", "bag"],
  ["cable-2-5", "ELE-001", "2.5 mm² copper cable", "material", "m"],
  ["conduit-20", "ELE-002", "20 mm PVC conduit", "material", "m"],
  ["socket-13a", "ELE-003", "13A switched socket outlet", "material", "nr"],
  ["back-box", "ELE-004", "Electrical back box and accessories", "material", "nr"],
  ["electrical-point-labour", "ELE-L01", "Electrical point installation labour", "labour", "point"],
  ["electrical-testing", "ELE-L02", "Testing and commissioning allowance", "labour", "point"],
  ["ppr-pipe-25", "MEC-001", "25 mm PPR cold-water pipe", "material", "m"],
  ["ppr-fitting-allowance", "MEC-002", "PPR fittings and accessories allowance", "material", "item"],
  ["soil-pipe-110", "MEC-003", "110 mm uPVC soil/waste pipe", "material", "m"],
  ["soil-fitting-allowance", "MEC-004", "Soil-pipe fittings allowance", "material", "item"],
  ["plumbing-point-labour", "MEC-L01", "Plumbing point installation labour", "labour", "point"],
  ["pipework-labour", "MEC-L02", "Pipework installation labour", "labour", "m"],
  ["longspan-roof-sheet", "ROF-001", "Longspan aluminium roofing sheet", "material", "m²"],
  ["roofing-accessories", "ROF-002", "Roofing screws, flashings and accessories allowance", "material", "item"],
  ["roofing-labour", "ROF-L01", "Roof covering installation labour", "labour", "m²"],
] .map(([id, code, description, category, unit]) => ({
  id,
  code,
  description,
  category: category as PriceItem["category"],
  unit,
  rate: starterRates[id] ?? null,
  defaultRate: starterRates[id] ?? null,
  currency: "NGN",
  countryCode: "NG",
  region: "FCT",
  location: "Abuja",
  source: "Charismak Nigeria starter reference - verify before commercial use",
  sourceUrl: null,
  confidence: "starter" as const,
  updatedAt: createdAt,
  active: true,
}));

export const DEFAULT_PRICE_ITEMS: PriceItem[] = [
  ...CORE_PRICE_ITEMS,
  ...AFRICA_PRICE_ITEMS,
];

const templateStarterRates: Record<string, number> = {
  "concrete-1-2-4": 135000,
  "blockwork-225": 15500,
  "reinforcement-fixed": 2500,
  "formwork-standard": 20000,
  "excavation-manual-normal": 7500,
  "plaster-15mm": 7500,
  "emulsion-paint-two-coats": 4500,
  "floor-tiling": 25000,
  "socket-outlet-point": 75000,
  "cold-water-point": 45000,
  "soil-pipe-110-installed": 18000,
  "longspan-roof-covering": 25000,
};

const concreteAssumptions = (
  cementRatio: number,
  sandRatio: number,
  aggregateRatio: number,
  waterLitresPerM3: number,
): RateAssumptionDefinition[] => [
  { id: "cementRatio", label: "Cement ratio", defaultValue: cementRatio, min: 0, step: 0.1 },
  { id: "sandRatio", label: "Sand ratio", defaultValue: sandRatio, min: 0, step: 0.1 },
  { id: "aggregateRatio", label: "Aggregate ratio", defaultValue: aggregateRatio, min: 0, step: 0.1 },
  { id: "dryVolumeFactor", label: "Dry-volume factor", defaultValue: 1.54, min: 1, step: 0.01, help: "Allowance converting finished wet concrete to dry constituents." },
  { id: "cementBagVolumeM3", label: "Cement bag volume", unit: "m³/bag", defaultValue: 0.0347, min: 0.001, step: 0.0001 },
  { id: "materialWastagePercent", label: "Material wastage", unit: "%", defaultValue: 5, min: 0, step: 0.5 },
  { id: "waterLitresPerM3", label: "Water allowance", unit: "L/m³", defaultValue: waterLitresPerM3, min: 0, step: 1 },
];

const CORE_RATE_TEMPLATES: RateTemplate[] = [
  {
    id: "concrete-1-2-4",
    code: "RATE-CON-001",
    name: "1:2:4 Concrete",
    description: "Provide, mix, place and compact nominal 1:2:4 concrete, including 5% material allowance.",
    unit: "m³",
    module: "concrete",
    category: "substructure",
    assumptions: concreteAssumptions(1, 2, 4, 166.43),
    formula: {
      type: "concrete-ratio" as const,
      componentIds: {
        cement: "con-cement",
        sand: "con-sand",
        aggregate: "con-granite",
        water: "con-water",
      },
    },
    components: [
      { id: "con-cement", priceItemId: "cement-50kg", description: "Cement", category: "material", quantityPerUnit: 6.657061 },
      { id: "con-sand", priceItemId: "sharp-sand", description: "Sharp sand", category: "material", quantityPerUnit: 0.462 },
      { id: "con-granite", priceItemId: "granite-aggregate", description: "Granite", category: "material", quantityPerUnit: 0.924 },
      { id: "con-water", priceItemId: "water", description: "Water", category: "material", quantityPerUnit: 166.426513 },
      { id: "con-labour", priceItemId: "concrete-labour", description: "Concrete labour", category: "labour", quantityPerUnit: 1 },
      { id: "con-plant", priceItemId: "concrete-mixer", description: "Mixer and small plant", category: "plant", quantityPerUnit: 1 },
    ],
  },
  {
    id: "blockwork-225",
    code: "RATE-BLK-001",
    name: "225 mm Blockwork",
    description: "Lay 225 mm sandcrete block wall in cement-sand mortar, including block and mortar allowances.",
    unit: "m²",
    module: "blockwork",
    category: "walls",
    components: [
      { id: "blk-block", priceItemId: "block-225", description: "225 mm blocks", category: "material", quantityPerUnit: 10.5 },
      { id: "blk-cement", priceItemId: "cement-50kg", description: "Mortar cement", category: "material", quantityPerUnit: 0.132 },
      { id: "blk-sand", priceItemId: "sharp-sand", description: "Mortar sand", category: "material", quantityPerUnit: 0.01815 },
      { id: "blk-water", priceItemId: "water", description: "Mortar water", category: "material", quantityPerUnit: 3.63 },
      { id: "blk-labour", priceItemId: "blockwork-labour", description: "Block laying labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "reinforcement-fixed",
    code: "RATE-REI-001",
    name: "Reinforcement Cutting and Fixing",
    description: "Supply, cut, bend and fix high-yield reinforcement including 5% steel allowance and binding wire.",
    unit: "kg",
    module: "reinforcement",
    category: "frame",
    components: [
      { id: "rei-steel", priceItemId: "reinforcement-steel", description: "Reinforcement steel", category: "material", quantityPerUnit: 1.05 },
      { id: "rei-wire", priceItemId: "binding-wire", description: "Binding wire", category: "material", quantityPerUnit: 0.01575 },
      { id: "rei-labour", priceItemId: "rebar-labour", description: "Cutting, bending and fixing labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "formwork-standard",
    code: "RATE-FRM-001",
    name: "Standard Plywood Formwork",
    description: "Provide, erect and strike plywood formwork with support timber, nails and three expected reuses.",
    unit: "m²",
    module: "formwork",
    category: "frame",
    components: [
      { id: "frm-sheet", priceItemId: "formwork-sheet", description: "Plywood sheet allocation", category: "material", quantityPerUnit: 0.123144 },
      { id: "frm-timber", priceItemId: "formwork-timber", description: "Support timber", category: "material", quantityPerUnit: 1.5 },
      { id: "frm-nails", priceItemId: "nails", description: "Nails", category: "material", quantityPerUnit: 0.1 },
      { id: "frm-labour", priceItemId: "formwork-labour", description: "Erection and striking labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "excavation-manual-normal",
    code: "RATE-EXC-001",
    name: "Manual Excavation in Normal Ground",
    description: "Excavate foundation trench or pit by hand in normal ground and trim formation.",
    unit: "m³",
    module: "excavation",
    category: "substructure",
    components: [
      { id: "exc-labour", priceItemId: "excavation-labour", description: "Excavation labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "plaster-15mm",
    code: "RATE-FIN-001",
    name: "15 mm Cement-Sand Plaster",
    description: "Prepare background and apply 15 mm cement-sand plaster; starter component allowances are editable.",
    unit: "m²",
    module: "finishes",
    category: "finishes",
    components: [
      { id: "pls-cement", priceItemId: "cement-50kg", description: "Cement", category: "material", quantityPerUnit: 0.09 },
      { id: "pls-sand", priceItemId: "sharp-sand", description: "Plastering sand", category: "material", quantityPerUnit: 0.0171 },
      { id: "pls-water", priceItemId: "water", description: "Water", category: "material", quantityPerUnit: 3 },
      { id: "pls-labour", priceItemId: "plaster-labour", description: "Plastering labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "emulsion-paint-two-coats",
    code: "RATE-FIN-002",
    name: "Emulsion Painting, Two Coats",
    description: "Prepare surface and apply two coats of emulsion paint; coverage allowances remain editable.",
    unit: "m²",
    module: "finishes",
    category: "finishes",
    components: [
      { id: "pnt-paint", priceItemId: "emulsion-paint", description: "Emulsion paint", category: "material", quantityPerUnit: 0.21 },
      { id: "pnt-filler", priceItemId: "wall-filler", description: "Wall filler", category: "material", quantityPerUnit: 0.1 },
      { id: "pnt-labour", priceItemId: "painting-labour", description: "Preparation and painting labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "floor-tiling",
    code: "RATE-FIN-003",
    name: "Selected Floor Tiling",
    description: "Lay selected floor tiles with adhesive, including starter waste allowances.",
    unit: "m²",
    module: "finishes",
    category: "finishes",
    components: [
      { id: "til-tile", priceItemId: "floor-tile", description: "Floor tile including waste", category: "material", quantityPerUnit: 1.05 },
      { id: "til-adhesive", priceItemId: "tile-adhesive", description: "Tile adhesive", category: "material", quantityPerUnit: 0.22 },
      { id: "til-labour", priceItemId: "tiling-labour", description: "Tiling labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "socket-outlet-point",
    code: "RATE-ELE-001",
    name: "13A Socket Outlet Point",
    description: "Wiring, conduit, box, outlet, installation, testing and commissioning. Route quantities are editable per project.",
    unit: "point",
    module: "electrical",
    category: "electrical",
    components: [
      { id: "soc-cable", priceItemId: "cable-2-5", description: "2.5 mm² cable", category: "material", quantityPerUnit: 15 },
      { id: "soc-conduit", priceItemId: "conduit-20", description: "20 mm conduit", category: "material", quantityPerUnit: 10 },
      { id: "soc-outlet", priceItemId: "socket-13a", description: "13A outlet", category: "material", quantityPerUnit: 1 },
      { id: "soc-box", priceItemId: "back-box", description: "Back box and accessories", category: "material", quantityPerUnit: 1 },
      { id: "soc-labour", priceItemId: "electrical-point-labour", description: "Installation labour", category: "labour", quantityPerUnit: 1 },
      { id: "soc-test", priceItemId: "electrical-testing", description: "Testing allowance", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "cold-water-point",
    code: "RATE-MEC-001",
    name: "Cold-Water Plumbing Point",
    description: "PPR pipework, fittings and labour to one cold-water point. Route quantities are editable per project.",
    unit: "point",
    module: "mechanical",
    category: "mechanical",
    components: [
      { id: "cwp-pipe", priceItemId: "ppr-pipe-25", description: "25 mm PPR pipe", category: "material", quantityPerUnit: 6 },
      { id: "cwp-fitting", priceItemId: "ppr-fitting-allowance", description: "Fittings allowance", category: "material", quantityPerUnit: 1 },
      { id: "cwp-labour", priceItemId: "plumbing-point-labour", description: "Installation labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "soil-pipe-110-installed",
    code: "RATE-MEC-002",
    name: "110 mm Soil/Waste Pipework",
    description: "Supply, install, joint and test 110 mm soil/waste pipework with fittings allowance.",
    unit: "m",
    module: "mechanical",
    category: "mechanical",
    components: [
      { id: "soil-pipe", priceItemId: "soil-pipe-110", description: "110 mm pipe including waste", category: "material", quantityPerUnit: 1.05 },
      { id: "soil-fitting", priceItemId: "soil-fitting-allowance", description: "Fittings allowance", category: "material", quantityPerUnit: 0.1 },
      { id: "soil-labour", priceItemId: "pipework-labour", description: "Installation labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
  {
    id: "longspan-roof-covering",
    code: "RATE-ROF-001",
    name: "Longspan Aluminium Roof Covering",
    description: "Supply and fix longspan aluminium roofing sheets with laps, screws, flashings and installation labour.",
    unit: "m²",
    module: "roofing",
    category: "roof",
    components: [
      { id: "rof-sheet", priceItemId: "longspan-roof-sheet", description: "Roofing sheet including laps and waste", category: "material", quantityPerUnit: 1.1 },
      { id: "rof-accessories", priceItemId: "roofing-accessories", description: "Fixings and accessories allowance", category: "material", quantityPerUnit: 0.05 },
      { id: "rof-labour", priceItemId: "roofing-labour", description: "Roofing installation labour", category: "labour", quantityPerUnit: 1 },
    ],
  },
].map((template): RateTemplate => ({
  ...template,
  components: template.components as RateTemplate["components"],
  defaultUnitRate: templateStarterRates[template.id] ?? null,
  diagramType: template.module,
}));

export const DEFAULT_RATE_TEMPLATES: RateTemplate[] = [
  ...CORE_RATE_TEMPLATES,
  ...AFRICA_RATE_TEMPLATES,
];
