export type SupplierFormGroup =
  | "Core materials"
  | "Finishes & envelope"
  | "MEP & building systems"
  | "Civil, site & safety"
  | "Tools, plant & equipment"
  | "Labour & specialists";

export type SupplierFormDefinition = {
  id: string;
  title: string;
  shortTitle: string;
  group: SupplierFormGroup;
  audience: string;
  formUrl: string;
  keywords: string[];
};

export const SUPPLIER_ENTRY_FORM_URL =
  "https://docs.google.com/forms/d/e/1FAIpQLScJeHtM0tkqV-B0IQSpJB856TZr__J4pRtlCDvZAa9DfqLSpw/viewform";

export const SUPPLIER_FORM_GROUPS: SupplierFormGroup[] = [
  "Core materials",
  "Finishes & envelope",
  "MEP & building systems",
  "Civil, site & safety",
  "Tools, plant & equipment",
  "Labour & specialists",
];

export const SUPPLIER_FORMS: SupplierFormDefinition[] = [
  {
    id: "F01",
    title: "Cement, Blocks & Concrete Prices",
    shortTitle: "Cement, Blocks & Concrete",
    group: "Core materials",
    audience: "Cement dealers, block makers, ready-mix and precast suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdkCxaz9Hdlx1igFiIIIshuc9m8C7i9yPdKTpbvkRuWRtZeCg/viewform",
    keywords: ["cement", "dangote", "bua", "lafarge", "block", "sandcrete", "ready mix", "precast", "concrete"],
  },
  {
    id: "F02",
    title: "Sand, Granite, Laterite & Bulk Material Prices",
    shortTitle: "Sand, Granite & Bulk Materials",
    group: "Core materials",
    audience: "Quarries, tipper owners and aggregate suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfDwng6xYTMjpwC1oDYrrtc0TN68HIQ8h2NDvI6lyH1dUQRPA/viewform",
    keywords: ["sand", "granite", "aggregate", "chippings", "laterite", "hardcore", "tipper", "quarry", "water tanker"],
  },
  {
    id: "F03",
    title: "Reinforcement & Structural Steel Prices",
    shortTitle: "Reinforcement & Structural Steel",
    group: "Core materials",
    audience: "Steel merchants, mills and fabricators",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfZVs4FB4EWJNiWJzFR-XfC_A8t7ufymp61xnt2m2az7ybe8A/viewform",
    keywords: ["steel", "rebar", "iron rod", "y12", "y16", "brc", "h beam", "i beam", "angle", "hollow section"],
  },
  {
    id: "F04",
    title: "Formwork, Timber & Board Prices",
    shortTitle: "Formwork, Timber & Boards",
    group: "Core materials",
    audience: "Timber dealers and plywood/formwork suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSd1Qw9K4KTVLMDgmBIudFSJhkLkvQPkZTOwxLtiWwHuVLDRtQ/viewform",
    keywords: ["timber", "plywood", "marine board", "formwork", "mdf", "hdf", "wood", "prop"],
  },
  {
    id: "F05",
    title: "Roofing, Cladding & Rainwater Prices",
    shortTitle: "Roofing, Cladding & Rainwater",
    group: "Finishes & envelope",
    audience: "Roofing sheet, ACP, polycarbonate and gutter suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSc9RvNciKZ_oCHtVludWd1VSzI-_bcIcYX7NvB7Y0Dh4xqxSw/viewform",
    keywords: ["roofing", "longspan", "stone coated", "aluminium", "gutter", "polycarbonate", "acp", "alucobond"],
  },
  {
    id: "F06",
    title: "Waterproofing, Insulation & Sealant Prices",
    shortTitle: "Waterproofing & Insulation",
    group: "Finishes & envelope",
    audience: "Waterproofing and insulation suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdCbQoQEW3t_zx7KVHWBhrCtrxrq3ENfCAD-KsViseYw_vRQw/viewform",
    keywords: ["waterproofing", "membrane", "dpc", "dpm", "insulation", "rockwool", "sealant", "silicone"],
  },
  {
    id: "F07",
    title: "Tiles, Flooring & Decorative Finish Prices",
    shortTitle: "Tiles, Flooring & Finishes",
    group: "Finishes & envelope",
    audience: "Tile, marble, granite, SPC, vinyl and finish suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfQqcTbvQMTfy2dX2QjJg83WOZ6yX77k0MKCU11H6WqtmIAyg/viewform",
    keywords: ["tile", "porcelain", "ceramic", "marble", "granite slab", "spc", "vinyl", "laminate", "carpet", "wallpaper"],
  },
  {
    id: "F08",
    title: "Ceiling, POP & Drywall Prices",
    shortTitle: "Ceiling, POP & Drywall",
    group: "Finishes & envelope",
    audience: "Gypsum, POP, suspended ceiling and partition suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfQxWYUSZqPnz-qY12zW1S67xkKO-f4oes9xArZ4LXAx_V97g/viewform",
    keywords: ["ceiling", "pop", "gypsum", "drywall", "partition", "stud", "track", "ceiling tile"],
  },
  {
    id: "F09",
    title: "Paint & Coating Prices",
    shortTitle: "Paint & Coatings",
    group: "Finishes & envelope",
    audience: "Paint manufacturers, dealers and coating suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSftpU__849BN9EcNM0cC1mp6qmlPer6MvPQ-U04aeA0xIC87w/viewform",
    keywords: ["paint", "emulsion", "dulux", "berger", "primer", "epoxy", "screed", "putty", "varnish"],
  },
  {
    id: "F10",
    title: "Doors, Windows & Ironmongery Prices",
    shortTitle: "Doors, Windows & Ironmongery",
    group: "Finishes & envelope",
    audience: "Door, window, lock and ironmongery suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeALsDFyIh81X0W-ibLKx2fvMQjEjyKcaHdn8r8P2AQxNo4GA/viewform",
    keywords: ["door", "window", "security door", "flush door", "lock", "hinge", "ironmongery", "upvc"],
  },
  {
    id: "F11",
    title: "Glass, Aluminium & Handrail Prices",
    shortTitle: "Glass, Aluminium & Handrails",
    group: "Finishes & envelope",
    audience: "Glass, aluminium, railing and facade suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeUVgtXFaowJvwt7TsxAnM_SvG028hcdcnoGvPWeOxewhmVng/viewform",
    keywords: ["glass", "tempered", "laminated", "mirror", "aluminium", "handrail", "balustrade", "facade"],
  },
  {
    id: "F12",
    title: "Plumbing Pipe, Fitting, Pump & Tank Prices",
    shortTitle: "Plumbing, Pumps & Tanks",
    group: "MEP & building systems",
    audience: "Plumbing merchants, pipe dealers and pump/tank suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfvIwwyNXOWMn_9oNUmgVNL6lKHdUHINxEFenLFk6PkS1BzQA/viewform",
    keywords: ["plumbing", "ppr", "pvc", "upvc", "pipe", "fitting", "pump", "water tank", "valve", "drain"],
  },
  {
    id: "F13",
    title: "Sanitary Ware & Bathroom Accessory Prices",
    shortTitle: "Sanitary Wares & Bathroom",
    group: "MEP & building systems",
    audience: "Sanitary ware and bathroom suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSd6fxAHw9vxOwBf5mwv0QxrLM1jSG00fCEHr4KtwsYg0Sw6-A/viewform",
    keywords: ["sanitary", "wc", "toilet", "basin", "shower", "mixer", "tap", "bathtub", "urinal", "sink"],
  },
  {
    id: "F14",
    title: "Fire Protection & Fire Alarm Prices",
    shortTitle: "Fire Protection & Alarm",
    group: "MEP & building systems",
    audience: "Firefighting and alarm equipment suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScWjt9k-INzH9wd9Ld8ZmsN8gclxs7tBFbc8LdFSkftRApWlA/viewform",
    keywords: ["fire", "extinguisher", "sprinkler", "hose reel", "hydrant", "alarm", "smoke detector"],
  },
  {
    id: "F15",
    title: "HVAC & Mechanical Prices",
    shortTitle: "HVAC & Mechanical",
    group: "MEP & building systems",
    audience: "AC, VRF, duct, fan and mechanical suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSd06FcEeu9E_f9pyUNbvrOzGeGTpCTuc4mBfLoBJ-REboM_Cw/viewform",
    keywords: ["hvac", "air conditioner", "ac", "vrf", "duct", "fan", "copper pipe", "refrigerant"],
  },
  {
    id: "F16",
    title: "Electrical Cable & Containment Prices",
    shortTitle: "Electrical Cable & Containment",
    group: "MEP & building systems",
    audience: "Cable, conduit, tray and trunking suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfHgBTm3mEVZGAiObJ4WHCTipbmn38nqTvap4SPbgUsidoc8Q/viewform",
    keywords: ["electrical", "cable", "wire", "armoured", "conduit", "tray", "trunking", "gland"],
  },
  {
    id: "F17",
    title: "Electrical Switchgear & Panel Prices",
    shortTitle: "Switchgear & Panels",
    group: "MEP & building systems",
    audience: "Electrical panel, MCB/MCCB and switchgear suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSd3xgt5n1Xl3VM-I_qHIO8XeKHLkJ6Lf08nqGHIglGNJwok3g/viewform",
    keywords: ["mcb", "mccb", "rcd", "db", "distribution board", "switchgear", "ats", "changeover", "panel"],
  },
  {
    id: "F18",
    title: "Electrical Accessories & Lighting Prices",
    shortTitle: "Electrical Accessories & Lighting",
    group: "MEP & building systems",
    audience: "Switch/socket and lighting suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSetyJbsznC7vbxMph5z1t7XmBIRgJFVvmZE3XuXyvFzNz4pvw/viewform",
    keywords: ["socket", "switch", "lighting", "led", "downlight", "floodlight", "street light", "floor box"],
  },
  {
    id: "F19",
    title: "Generator, Solar, Inverter & Earthing Prices",
    shortTitle: "Generator, Solar & Inverter",
    group: "MEP & building systems",
    audience: "Generator, transformer, inverter, solar and earthing suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdlonOMJFpx4nxQSa5mRmssopg91q0LOEz7hAfJbGDVLm9PDA/viewform",
    keywords: ["generator", "solar", "inverter", "battery", "panel", "transformer", "earthing", "lightning"],
  },
  {
    id: "F20",
    title: "ICT, CCTV, Access Control & Security Prices",
    shortTitle: "ICT, CCTV & Security",
    group: "MEP & building systems",
    audience: "Network, CCTV, access-control and security suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdx8ByRFKHXWh8v6JZnxxN6zq9G-sCkx9MXO5fm8dmt-apVXQ/viewform",
    keywords: ["ict", "network", "cat6", "cctv", "camera", "nvr", "access control", "security", "electric fence"],
  },
  {
    id: "F21",
    title: "External Works, Drainage & Road Material Prices",
    shortTitle: "External Works & Road Materials",
    group: "Civil, site & safety",
    audience: "Civil, drainage, road and geosynthetic suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScaJ0LtVpe_-IQfhNYx-oaQmrXMAoga6k7u2pG-1Gj2cKX1wA/viewform",
    keywords: ["civil", "drainage", "road", "geotextile", "gabion", "hdpe", "asphalt", "bitumen", "kerb"],
  },
  {
    id: "F22",
    title: "Landscaping Material Prices",
    shortTitle: "Landscaping Materials",
    group: "Civil, site & safety",
    audience: "Nurseries, turf and landscape-material suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdOcVUqgnRkSx2sdQD2ehP5pogASIGjRXjXVUNjDMWPjw4gsg/viewform",
    keywords: ["landscaping", "grass", "turf", "topsoil", "fertilizer", "plant", "tree", "irrigation"],
  },
  {
    id: "F23",
    title: "PPE & Site Consumable Prices",
    shortTitle: "PPE & Site Consumables",
    group: "Civil, site & safety",
    audience: "PPE and site-consumable suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSexMpp9p5-O0VNLT2AjIHwQbdAED8_VthtlhzQmE_F5DSXRJg/viewform",
    keywords: ["ppe", "safety", "helmet", "boot", "vest", "harness", "gloves", "first aid", "tarpaulin"],
  },
  {
    id: "F24",
    title: "Fastener, Hardware & Welding Consumable Prices",
    shortTitle: "Fasteners, Hardware & Welding",
    group: "Civil, site & safety",
    audience: "Hardware and welding consumable suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSexsOvaT2NdAd3FXf3LNvxbflSSNpHTKWkUDNXlccyvfvwDzg/viewform",
    keywords: ["nail", "screw", "bolt", "anchor", "welding", "electrode", "cutting disc", "hardware"],
  },
  {
    id: "F25",
    title: "Hand Tool Prices",
    shortTitle: "Hand Tools",
    group: "Tools, plant & equipment",
    audience: "Tool and hardware suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdNsqvmb7i-8Ctz3C5dc8ruS4JCYmo9_bj8Mn0NOHBqE8W4yg/viewform",
    keywords: ["hand tool", "shovel", "hammer", "trowel", "spirit level", "measuring tape", "wheelbarrow"],
  },
  {
    id: "F26",
    title: "Power Tool Prices",
    shortTitle: "Power Tools",
    group: "Tools, plant & equipment",
    audience: "Power-tool dealers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScEgHaoABCd2KroYRzLzYXtmlhxwnIZ0n4durg-Zy6qhmMi8g/viewform",
    keywords: ["power tool", "grinder", "drill", "saw", "demolition hammer", "tile cutter", "bosch", "makita"],
  },
  {
    id: "F27",
    title: "Light Plant & Site Equipment Prices",
    shortTitle: "Light Plant & Site Equipment",
    group: "Tools, plant & equipment",
    audience: "Small plant dealers and hire companies",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScsUe980mN_KEtY1MgOftKd54h-thxrxOfwMpFYMoxviYFGig/viewform",
    keywords: ["mixer", "vibrator", "plate compactor", "rammer", "power trowel", "road cutter", "welding machine", "small plant"],
  },
  {
    id: "F28",
    title: "Scaffolding & Access Equipment Prices",
    shortTitle: "Scaffolding & Access",
    group: "Tools, plant & equipment",
    audience: "Scaffold/access suppliers and hire firms",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSc-uqScB8IcD_92UQvEvnrpq3OtgRhKcRo8-IHTbOBRULVULw/viewform",
    keywords: ["scaffold", "cuplock", "prop", "ladder", "mobile tower", "access equipment"],
  },
  {
    id: "F29",
    title: "Heavy Plant & Earthmoving Hire/Purchase Prices",
    shortTitle: "Heavy Plant & Earthmoving",
    group: "Tools, plant & equipment",
    audience: "Equipment dealers, plant-hire companies and contractors",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf4I0td-bpnU8Fd6CrWvL_OZkLEKVVbELBnEIgnJ1gJ5PSV8Q/viewform",
    keywords: ["excavator", "bulldozer", "grader", "roller", "loader", "tipper", "earthmoving", "heavy plant"],
  },
  {
    id: "F30",
    title: "Crane, Lifting & Concrete Plant Prices",
    shortTitle: "Cranes, Lifting & Concrete Plant",
    group: "Tools, plant & equipment",
    audience: "Crane, forklift, access and concrete-equipment companies",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf2a37fl9V_EPwKQu8ZaZUZgCJz6BHLO_8g20PZFJPIFJpvQw/viewform",
    keywords: ["crane", "forklift", "telehandler", "manlift", "scissor lift", "concrete pump", "batching plant", "transit mixer"],
  },
  {
    id: "F31",
    title: "Roadwork, Piling & Specialist Civil Plant Prices",
    shortTitle: "Roadwork, Piling & Civil Plant",
    group: "Tools, plant & equipment",
    audience: "Specialist civil contractors and plant-hire companies",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfzECoFcxfq4k8-G7Ddj9XD_ZpqZEDNP7Hme53KpW_x3wlbXg/viewform",
    keywords: ["asphalt paver", "milling", "piling rig", "vibro hammer", "crawler crane", "drilling rig", "roadwork"],
  },
  {
    id: "F32",
    title: "Surveying & Testing Equipment Prices",
    shortTitle: "Surveying & Testing Equipment",
    group: "Tools, plant & equipment",
    audience: "Survey and QA/QC equipment suppliers and hire companies",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLScHXMPTQBIDvcrObXeAfzzxzd00QwCTqtfWC0_s9q1S0sCM7w/viewform",
    keywords: ["survey", "total station", "level", "rtk", "cube mould", "slump", "testing", "megger", "multimeter"],
  },
  {
    id: "F33",
    title: "Temporary Works & Site Facility Prices",
    shortTitle: "Temporary Works & Site Facilities",
    group: "Tools, plant & equipment",
    audience: "Container, cabin, fencing and temporary-power suppliers",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeXFeBrqBCzPqrxjoHZ0oc4GbcnEPN4GCZecAlWk3CdOGe0Xg/viewform",
    keywords: ["container", "site office", "cabin", "temporary fence", "hoarding", "site facility", "temporary power"],
  },
  {
    id: "F34",
    title: "Labour & Specialist Trade Rate Update",
    shortTitle: "Labour & Specialist Trades",
    group: "Labour & specialists",
    audience: "Artisans, subcontractors and specialist contractors",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSd4hh1bOxzUyfXfa4Owy0avPmj_oqMCqGk04hdSx6_VzXPxfw/viewform",
    keywords: ["labour", "artisan", "subcontractor", "tiling", "plumbing", "electrical", "painting", "roofing", "fabrication", "borehole"],
  },
];
